version: '3'

services:
  postgres:
    image: postgres:13.1
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=my-budget
    volumes:
      - ./db-datas:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db-datas:
